#!/usr/bin/env python3
# Copyright (C) 2026 wolfSSL Inc.
#
# This file is part of wolfHSM.
#
# wolfHSM is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
"""
Generate wh_test_list.c from WH_TEST_{MISC,CLIENT,SERVER} annotations.

For every test found it emits:
  - A `WH_TEST_DECL(name);` line, which expands (see
    wh_test_list.h) to a forward prototype plus a weak skip
    implementation returning WH_TEST_SKIPPED. When the real
    test's feature gate is on, its strong definition overrides
    this stub at link time; otherwise the stub wins and the
    test surfaces as SKIPPED at runtime.
  - A row in whTests[].

Preprocessor conditionals around the annotation are deliberately
ignored: the link-time weak override handles the gating. All the
script needs is the set of annotated function names and the group
each belongs to.

Usage:
    gen_test_list.py --output <path> <source-dir>...
"""

import argparse
import os
import re
import sys

ANNOTATION_RE = re.compile(
    r'^\s*WH_TEST_(MISC|CLIENT|SERVER)\s+int\s+(\w+)\s*\(',
    re.MULTILINE,
)

# Strip // line comments and /* ... */ block comments so an
# annotation appearing in commented-out code doesn't register a
# phantom test. Strings aren't stripped; an annotation inside a
# string literal would be an exotic footgun we're not solving.
LINE_COMMENT_RE  = re.compile(r'//[^\n]*')
BLOCK_COMMENT_RE = re.compile(r'/\*.*?\*/', re.DOTALL)

# Each group emits its own whTests<Group>[] registry in the
# generated file. Order here fixes the section ordering in
# wh_test_list.c.
GROUPS = [
    ('MISC',   'whTestsMisc',   'whTestsMiscCount'),
    ('SERVER', 'whTestsServer', 'whTestsServerCount'),
    ('CLIENT', 'whTestsClient', 'whTestsClientCount'),
]


def strip_comments(src):
    src = BLOCK_COMMENT_RE.sub('', src)
    src = LINE_COMMENT_RE.sub('', src)
    return src


def scan_file(path):
    """Return [(group, fn_name)] from one source file."""
    with open(path, 'r') as f:
        src = strip_comments(f.read())
    return [(m.group(1), m.group(2)) for m in ANNOTATION_RE.finditer(src)]


def discover(dirs):
    """Walk dirs, scan .c files, return sorted unique tests with stable group-major order."""
    found = []
    seen_names = {}
    for d in dirs:
        for root, _, files in os.walk(d):
            for name in sorted(files):
                if not name.endswith('.c'):
                    continue
                path = os.path.join(root, name)
                for group, fn in scan_file(path):
                    if fn in seen_names:
                        prev = seen_names[fn]
                        sys.stderr.write(
                            "gen_test_list.py: duplicate test name '{}' "
                            "(in {} and {})\n".format(fn, prev, path))
                        sys.exit(1)
                    seen_names[fn] = path
                    found.append((group, fn, path))
    # Stable order: group (misc/server/client), then discovery order.
    group_order = {g[0]: i for i, g in enumerate(GROUPS)}
    found.sort(key=lambda t: (group_order[t[0]], t[2], t[1]))
    return found


HEADER = """\
/*
 * Copyright (C) 2026 wolfSSL Inc.
 *
 * This file is part of wolfHSM.
 *
 * wolfHSM is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * wolfHSM is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with wolfHSM.  If not, see <http://www.gnu.org/licenses/>.
 */

/*
 *************************************************************************
 * wh_test_list.c -- GENERATED BY gen_test_list.py. DO NOT EDIT.
 *************************************************************************
 */

/*
 * Registry of every test function found via WH_TEST_{MISC,
 * CLIENT,SERVER} annotations. Each discovered test gets a weak
 * stub that returns WH_TEST_SKIPPED; the real test, when
 * compiled in, provides a strong symbol that the linker picks
 * instead.
 */

#include "wh_test_list.h"

"""


def render(tests):
    out = [HEADER]

    # Declarations and weak skip implementations -- one per test.
    # WH_TEST_DECL expands to a forward prototype plus a weak
    # stub returning WH_TEST_SKIPPED; the real test's strong
    # definition overrides it at link time when the feature gate
    # is on.
    out.append(
        '/* Test declarations and weak skip implementations. '
        '*/\n')
    for group, fn, _ in tests:
        out.append('WH_TEST_DECL({name});\n'.format(name=fn))
    out.append('\n')

    # Per-group registration tables.
    by_group = {g[0]: [] for g in GROUPS}
    for group, fn, _ in tests:
        by_group[group].append(fn)

    for i, (group, array, count) in enumerate(GROUPS):
        fns = by_group[group]
        if i > 0:
            out.append('\n')
        if not fns:
            # C forbids zero-length arrays at file scope; emit a
            # single NULL placeholder and a hardcoded count of 0
            # so the runner treats this group as empty.
            out.append(
                'const whTestCase {array}[] = '
                '{{ {{ NULL, NULL }} }};\n'.format(array=array))
            out.append('const size_t {count} = 0;\n'.format(count=count))
            continue
        out.append('const whTestCase {array}[] = {{\n'.format(array=array))
        for fn in fns:
            out.append(
                '    {{ "{name}", {name} }},\n'.format(name=fn))
        out.append('};\n')
        out.append(
            'const size_t {count} = '
            'sizeof({array}) / sizeof({array}[0]);\n'.format(
                array=array, count=count))

    return ''.join(out)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--output', required=True,
                    help='path to wh_test_list.c to (re)generate')
    ap.add_argument('sources', nargs='+',
                    help='test source directories to scan')
    args = ap.parse_args()

    tests = discover(args.sources)
    if not tests:
        sys.stderr.write('gen_test_list.py: no WH_TEST_* annotations found\n')
        sys.exit(1)

    new_content = render(tests)

    # Only rewrite when content actually changes, so make doesn't
    # rebuild the world on every invocation.
    try:
        with open(args.output, 'r') as f:
            if f.read() == new_content:
                return
    except IOError:
        pass

    with open(args.output, 'w') as f:
        f.write(new_content)


if __name__ == '__main__':
    main()
