/*
 * Copyright (C) 2026 wolfSSL Inc.
 *
 * This file is part of wolfHSM.
 *
 * wolfHSM is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * wolfHSM is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with wolfHSM.  If not, see <http://www.gnu.org/licenses/>.
 */

/*
 *************************************************************************
 * wh_test_list.c -- GENERATED BY gen_test_list.py. DO NOT EDIT.
 *************************************************************************
 */

/*
 * Registry of every test function found via WH_TEST_{MISC,
 * CLIENT,SERVER} annotations. Each discovered test gets a weak
 * stub that returns WH_TEST_SKIPPED; the real test, when
 * compiled in, provides a strong symbol that the linker picks
 * instead.
 */

#include "wh_test_list.h"

/* Test declarations and weak skip implementations. */
WH_TEST_DECL(whTest_FlashEraseProgramVerify);
WH_TEST_DECL(whTest_FlashWriteLock);
WH_TEST_DECL(whTest_FlashUnitOps);
WH_TEST_DECL(whTest_NvmAddOverwriteDestroy);
WH_TEST_DECL(whTest_CertVerify);
WH_TEST_DECL(whTest_CryptoAes);
WH_TEST_DECL(whTest_CryptoEcc256);
WH_TEST_DECL(whTest_CryptoSha256);
WH_TEST_DECL(whTest_Echo);
WH_TEST_DECL(whTest_ServerInfo);

const whTestCase whTestsMisc[] = {
    { "whTest_FlashEraseProgramVerify", whTest_FlashEraseProgramVerify },
    { "whTest_FlashWriteLock", whTest_FlashWriteLock },
    { "whTest_FlashUnitOps", whTest_FlashUnitOps },
    { "whTest_NvmAddOverwriteDestroy", whTest_NvmAddOverwriteDestroy },
};
const size_t whTestsMiscCount = sizeof(whTestsMisc) / sizeof(whTestsMisc[0]);

const whTestCase whTestsServer[] = {
    { "whTest_CertVerify", whTest_CertVerify },
};
const size_t whTestsServerCount = sizeof(whTestsServer) / sizeof(whTestsServer[0]);

const whTestCase whTestsClient[] = {
    { "whTest_CryptoAes", whTest_CryptoAes },
    { "whTest_CryptoEcc256", whTest_CryptoEcc256 },
    { "whTest_CryptoSha256", whTest_CryptoSha256 },
    { "whTest_Echo", whTest_Echo },
    { "whTest_ServerInfo", whTest_ServerInfo },
};
const size_t whTestsClientCount = sizeof(whTestsClient) / sizeof(whTestsClient[0]);
